#!/usr/bin/env python
# -*- coding: utf-8 vi:ts=4:noexpandtab
# Gstreamer examples build script

def options(opt):
	opt.load('compiler_c')
	opt.load('compiler_cxx')
	opt.recurse('merger')

def configure(conf):
	conf.load('compiler_c')
	conf.load('compiler_cxx')
	if conf.env.CC_NAME in ('gcc',):
		conf.env.CXXFLAGS += ['-std=c++11']
	conf.check_cfg(package='gstreamer-1.0', args='--cflags --libs', uselib_store="GST")
	conf.check_cfg(package='gstreamer-video-1.0', args='--cflags --libs', uselib_store="GST_VIDEO")
	conf.recurse('merger')

def build(bld):
	bld.recurse('merger')
