#!/usr/bin/env python
# -*- coding: utf-8 vi:ts=4:noexpandtab

def options(opt):
	opt.load('compiler_c')
	opt.load('compiler_cxx')

def configure(conf):
	conf.load('compiler_c')
	conf.load('compiler_cxx')
	if conf.env.CC_NAME in ('gcc',):
                conf.env.CXXFLAGS += ['-std=c++11']
	conf.check_cfg(package='gstreamer-1.0', args='--cflags --libs', uselib_store="GST")
	conf.check_cfg(package='gstreamer-video-1.0', args='--cflags --libs', uselib_store="GST_VIDEO")

def build(bld):
	bld(
	 target='gstplugin',
	 features='c',
	 source='gstplugin.c',
	 use=["GST", "GST_VIDEO", 'cshlib'],
	 cflags=['-std=c99'],
	)

	bld(
	 target='gst-merger',
	 features='c cxx cxxshlib',
	 use="gstplugin",
	)

